### ISSUE TITLE
Cannot export events in csv while using the simultor on Windows 10

### ISSUE THREAD

**Issue by omarzia88** [knowgoio/knowgo-vehicle-simulator#7]
Are there any particular settings or permissions needed to export csv files in the windows version of the simulator? Because the web version can do it but the local windows cannot, It helds up when I try to do it.

**Comment by pmundt** [comment]
Thanks for the report, @omarzia88. Indeed, there were two bugs, one was that we were using a hardcoded path separator, and the other the fact that Windows apparently can't handle :'s in filenames. I've fixed both of these now and will push the fixes momentarily.
