### ISSUE TITLE
REST api call

### ISSUE THREAD

**Issue by omarzia88** [knowgoio/knowgo-vehicle-simulator#8]
Hi, 
I would like to know if there are any API calls to update the status of the simulated vehicle i.e. Parameters like acceleration, braking, steering angle, and others that are accessible through the interface. I have checked the documentation it describes a POST request(/simulator/events) but it requires a host of parameters that I don't have in my environment e.g lat , long, etc.If there is a way please let me know, your help will be much appreciated.

**Comment by pmundt** [comment]
Yes, you can update the vehicle state through the REST API by POST'ing an event to the `/simulator/events` endpoint. The payload you submit here will be merged on the next event tick together with the generated event, so you only need to provide values for the items you specifically want to modify. All fields are optional. The endpoint itself takes an array of events, so you can submit one or more updates as you like and they will simply be buffered up and merged/drained on each subsequent tick.

**Comment by omarzia88** [comment]
Can you share a sample POST request on **/simulator/events** with a sample payload, Because I cannot find it on the postman collection you guys have shared in the documentation. Your help is greatly appreciated.

**Comment by omarzia88** [comment]
Thanks alot for your help.
