### ISSUE TITLE
REST Api server hangs up

### ISSUE THREAD

**Issue by omarzia88** [knowgoio/knowgo-vehicle-simulator#9]
When i try to Send a post Request "/simulator/events" script. For the first attempt, it works but when I try to send another request the application server hangs up. I am currently using the windows application. Please guide me which version of the application is most stable, Windows, Linux, or Android.I have tried to use the android version but I cannot send the API request to it from my laptop.Help will be greatly appreciated.

Regards,

Omar Zia

**Comment by pmundt** [comment]
Thanks, it looks like it was a problem when sending partial event updates and the webhook processing expecting a full event payload. I've fixed this now, and have verified that it works with sending multiple partial updates.
